apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- postgres.yaml
- sa.yaml

configMapGenerator:
- name: coregonus-db-jwt-config
  files:
  - jwt-config.json

commonLabels:
  app: coregonus-db
  tier: backend

namespace: app