apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-service.yaml
- configmap.yaml
- operator-service-account-rbac.yaml
- pg-system-namespace.yaml
- postgres-operator-deployment.yaml
- user-facing-clusterroles.yaml

commonLabels:
  app: postgres-operator
  component: operator
  tier: resources

namespace: pg-system